server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: bank
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"
  profiles:
    active:
      - "qa"
build:
  version: "3.0"
account:
  message: "Welcome to Bank API Services"
  contactDetails:
    name: "Lekha Gunasekaran - Developer"
    email: "lekha@bank.com"
  onCallSupport:
    -(909) 909-9090
    -(909) 909-9099