spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to  Loans Management Production Team"
  contactDetails:
    name: "lekha Gunasekaran"
    email: "lekha@bank.com"
  onCallSupport:
    - (707) 707-7070
    - (707) 070-0707