FROM eclipse-temurin:21-jdk
LABEL "org.opencontainers.image.authors"="Lekha Gunasekaran"
COPY target/account-0.0.1-SNAPSHOT.jar account-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","account-0.0.1-SNAPSHOT.jar"]