services:
  account:
    image: "lekhagunasekaran/account:v1"
    container_name: "Account-MS"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  loans:
    image: "lekhagunasekaran/loans:v1"
    container_name: "Loans-MS"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  cards:
    image: "lekhagunasekaran/cards:v1"
    container_name: "Cards-MS"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
networks:
  bank:
    driver: "bridge"